language: node_js
node_js:
- '8'
branchs:
  only:
  - master
install:
- npm install
services:
- docker
before_install:
- mkdir ~/.ssh
- openssl aes-256-cbc -K $encrypted_5566a038379e_key -iv $encrypted_5566a038379e_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh root@1106.54.71.232 -o StrictHostKeyChecking=no 'cd ~/blog-front && git pull origin master'
