language: node_js
node_js:
  - '8'
branchs:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_5566a038379e_key -iv $encrypted_5566a038379e_iv
    -in id_rsa.enc -out id_rsa -d
#  - ls -all
install:
  - npm install
script:
  - npm run build
after_success:
  - chmod 600 ./id_rsa
  - ssh root@106.54.71.232 -o StrictHostKeyChecking=no -i ./id_rsa 'cd /home/chengshan/github && git pull && ls -all && exit;'
